version: '2'
services:
  revealmd:
    image: tkaefer/reveal-md-container:latest
    volumes_from:
      - presentation
  presentation:
    image: some-container-volume-image-providing-the-presentation
    volumes:
      - /app
